/**
 * Build-time content pipeline. Runs before `vite` / `vite-react-ssg build`.
 *
 *  1. Reads the Markdown Builds in /content/builds, parses the frontmatter,
 *     renders Why and Stack to HTML, parses the Log into tagged Entries,
 *     derives the Build status, and writes src/content/builds.generated.ts.
 *  2. Regenerates public/sitemap.xml from the static routes plus the Builds.
 *
 * Both outputs are gitignored build artifacts. Edit the Markdown, not the
 * generated files. Format reference: content/builds/README.md.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';
import DOMPurify from 'isomorphic-dompurify';

const SITE = 'https://davidrydberg.dev';
const ROOT = process.cwd();
const BUILDS_DIR = join(ROOT, 'content', 'builds');
const GEN_FILE = join(ROOT, 'src', 'content', 'builds.generated.ts');
const SITEMAP_FILE = join(ROOT, 'public', 'sitemap.xml');

const TAGS = ['TRIED', 'WORKS', 'BROKE', 'SHIPPED', 'PARKED', 'DEAD', 'NOTE'];
const STATUS_BY_TAG = { SHIPPED: 'Shipped', PARKED: 'Parked', DEAD: 'Dead' };
const ENTRY_RE = /^(\d{4}-\d{2}-\d{2})(?:\s+(\d{2}:\d{2}))?\s+([A-Z]+)\s+(.*)$/;

const today = new Date().toISOString().slice(0, 10);

const render = (md) => DOMPurify.sanitize(marked.parse(md.trim(), { async: false }));

const toISODate = (d) => {
  if (!d) return today;
  if (d instanceof Date) return d.toISOString().slice(0, 10);
  return String(d).slice(0, 10);
};

/** Split the body into { why, stack, log } by its H2 headings. */
const sections = (body) => {
  const out = { why: '', stack: '', log: '' };
  let current = null;
  for (const line of body.split('\n')) {
    const h = line.match(/^##\s+(.+?)\s*$/);
    if (h) {
      current = h[1].toLowerCase();
      if (!(current in out)) current = null;
      continue;
    }
    if (current) out[current] += line + '\n';
  }
  return out;
};

/** Parse the Log section into Entries. Lines under an Entry are its detail. */
const parseLog = (text, file) => {
  const entries = [];
  let detail = [];
  const flush = () => {
    if (!entries.length) return;
    const md = detail.join('\n').trim();
    if (md) entries[entries.length - 1].detailHtml = render(md);
    detail = [];
  };
  for (const line of text.split('\n')) {
    const m = line.match(ENTRY_RE);
    if (m) {
      flush();
      const [, date, time, tag, body] = m;
      if (!TAGS.includes(tag)) {
        throw new Error(`[build-content] ${file}: unknown tag "${tag}" on ${date}`);
      }
      entries.push({ date, ...(time ? { time } : {}), tag, text: body.trim() });
    } else {
      detail.push(line);
    }
  }
  flush();
  // Newest first. Stable, so same-day entries keep file order reversed.
  const key = (e) => `${e.date} ${e.time ?? '00:00'}`;
  return entries
    .map((e, i) => ({ e, i }))
    .sort((a, b) => (key(a.e) < key(b.e) ? 1 : key(a.e) > key(b.e) ? -1 : b.i - a.i))
    .map(({ e }) => e);
};

const readBuilds = () => {
  if (!existsSync(BUILDS_DIR)) return [];
  const files = readdirSync(BUILDS_DIR).filter((f) => f.endsWith('.md') && f !== 'README.md');
  const builds = [];

  for (const file of files) {
    const slug = file.replace(/\.md$/, '');
    const { data, content } = matter(readFileSync(join(BUILDS_DIR, file), 'utf8'));
    if (data.draft === true) continue;

    const { why, stack, log } = sections(content);
    const entries = parseLog(log, file);
    const statusEntry = entries.find((e) => e.tag in STATUS_BY_TAG);
    const started = toISODate(data.started);

    builds.push({
      slug,
      path: `/builds/${slug}`,
      title: String(data.title ?? slug),
      oneliner: String(data.oneliner ?? ''),
      status: statusEntry ? STATUS_BY_TAG[statusEntry.tag] : 'Building',
      started,
      updated: entries[0]?.date ?? started,
      links: Array.isArray(data.links)
        ? data.links.map((l) => ({ label: String(l.label), url: String(l.url) }))
        : [],
      whyHtml: render(why),
      stackHtml: render(stack),
      log: entries,
    });
  }

  builds.sort((a, b) => (a.updated < b.updated ? 1 : -1));
  return builds;
};

const writeBuilds = (builds) => {
  mkdirSync(join(ROOT, 'src', 'content'), { recursive: true });
  const body = `// AUTO-GENERATED by scripts/build-content.mjs. Do not edit by hand.
// Edit the Markdown in /content/builds instead.
import type { Build } from './buildTypes';

export const BUILDS: Build[] = ${JSON.stringify(builds, null, 2)};
`;
  writeFileSync(GEN_FILE, body, 'utf8');
  console.log(`[build-content] wrote ${builds.length} build(s) to builds.generated.ts`);
};

const urlBlock = ({ loc, lastmod, changefreq, priority }) =>
  `  <url>\n    <loc>${SITE}${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n` +
  `    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;

const writeSitemap = (builds) => {
  const entries = [
    { loc: '/', lastmod: today, changefreq: 'weekly', priority: '1.0' },
    { loc: '/builds', lastmod: builds[0]?.updated ?? today, changefreq: 'weekly', priority: '0.9' },
    ...builds.map((b) => ({ loc: b.path, lastmod: b.updated, changefreq: 'weekly', priority: '0.8' })),
  ];
  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    entries.map(urlBlock).join('\n') +
    `\n</urlset>\n`;
  writeFileSync(SITEMAP_FILE, xml, 'utf8');
  console.log(`[build-content] wrote sitemap with ${entries.length} URLs`);
};

const builds = readBuilds();
writeBuilds(builds);
writeSitemap(builds);
