#!/usr/bin/env bash
# Generate showcase Builds from the public daily logs and open a PR for David to review.
#
# Usage:
#   scripts/showcase.sh             # read public/ from the logs repo's main
#   scripts/showcase.sh <logs-ref>  # read public/ from another branch or commit
#
# Reads only public/ and public-banned.txt from the private repo davidrydberg/logs.
# Claude may only write content/builds/*.md files marked `source: logs`; hand-written Builds are left alone.
# Nothing is merged. The PR is the review step.

set -euo pipefail

export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:/usr/bin:/bin:$PATH"

SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOGS_REF="${1:-main}"
BRANCH="showcase/$(date +%Y-%m-%d-%H%M)"
WORK="$(mktemp -d)"
trap 'git -C "$SITE_DIR" worktree remove --force "$WORK/site" 2>/dev/null || true; rm -rf "$WORK"' EXIT

fail() { echo "showcase: $*" >&2; exit 1; }

git -C "$SITE_DIR" fetch -q origin main
git -C "$SITE_DIR" worktree add -q -b "$BRANCH" "$WORK/site" origin/main
ln -s "$SITE_DIR/node_modules" "$WORK/site/node_modules"

mkdir "$WORK/logs"
gh api "repos/davidrydberg/logs/tarball/$LOGS_REF" > "$WORK/logs.tgz"
tar -xzf "$WORK/logs.tgz" -C "$WORK/logs" --strip-components=1 '*/public' '*/public-banned.txt'
[ -d "$WORK/logs/public" ] || fail "no public/ in davidrydberg/logs at $LOGS_REF"

PUBLIC_REPOS="$(gh repo list davidrydberg --visibility public --limit 200 --json url --jq '.[].url')"

cd "$WORK/site"
# The prompt goes on stdin: --tools and --add-dir take several values and would swallow it.
printf '%s\n\nLogs directory: %s\nPublic repos:\n%s\n' \
  "$(cat "$SITE_DIR/scripts/showcase-prompt.md")" "$WORK/logs/public" "$PUBLIC_REPOS" \
  | claude -p --strict-mcp-config --no-session-persistence --model claude-opus-5-5 \
    --tools "Read,Glob,Grep,Write,Edit" --permission-mode acceptEdits \
    --add-dir "$WORK/logs/public" > "$WORK/claude.out"

CHANGED="$(git status --porcelain --untracked-files=all | sed 's/^...//')"
[ -n "$CHANGED" ] || { echo "showcase: nothing new worth showing"; exit 0; }

# Guards: only generated Builds change, and nothing banned reaches the public repo.
while IFS= read -r f; do
  [[ "$f" == content/builds/*.md && "$f" != content/builds/README.md ]] || fail "touched $f"
  [ -f "$f" ] || fail "deleted $f"
  grep -q '^source: logs$' "$f" || fail "$f is not marked source: logs"
  if git cat-file -e "origin/main:$f" 2>/dev/null; then
    git show "origin/main:$f" | grep -q '^source: logs$' || fail "edited hand-written $f"
  fi
  ! grep -qiE -f "$WORK/logs/public-banned.txt" "$f" || fail "banned term in $f"
done <<< "$CHANGED"

node scripts/build-content.mjs > /dev/null

git add content/builds
git commit -q -m "Update showcase Builds from the logs"
git push -q -u origin "$BRANCH"
gh pr create --base main --head "$BRANCH" --title "Showcase Builds from the logs, $(date +%Y-%m-%d)" --body "Generated by \`scripts/showcase.sh\` from \`public/\` in davidrydberg/logs at \`$LOGS_REF\`.

Changed:
$(printf '%s\n' "$CHANGED" | sed 's/^/- /')

Read every Entry before merging. Check that no client can be identified."
